name: Aràlia
favicon: null
layout_spectrum: 0.10819748882204294
typography_spectrum: 0.00404
title: 'On tot és possible!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f9eb3'
    - '#002c77'
    - '#56dff9'
    - '#258ac4'
    - '#dee9f0'
  brandStrength: 0.6736870426684618
  lightness: 0.5923334001563489
  saturation: 0.91206024447456
  rhythmicContrast: 0.3945256853476167
purpose: []
