name: Aràlia
favicon: null
layout_spectrum: 0.23372
typography_spectrum: 0.04911
title: "No tinguis por dels canvis lents, només tingue'n de permanèixer immòbil."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#156683'
    - '#9db8ce'
    - '#f8a691'
    - '#9d8779'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.91206024447456
  rhythmicContrast: 0.3945256853476167
purpose: []
